import Head from "next/head";
import Carousol from "../components/Home/carousol";
import FeatureCards from "../components/Home/cards";
import About from "../components/Home/about";
import Posts from "../components/Home/posts";
import Gallery from "../components/Home/gallery";
import ContactForm from "../components/contactForm";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Our NGO APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div></div>
      <Carousol />
      <FeatureCards />
      <About />
      <Posts />
      <ContactForm />
      <Gallery />
    </div>
  );
}
